bitcoinsearch/tldr

src/app/components/client/homepage.tsx
src/app/components/server/post.tsx
src/app/globals.css

this parses the `-`s in the homepage summary and puts them into `<li>`s.

unordered list items for dashes on homepage

---

src/app/components/client/homepage.tsx
src/app/components/server/post.tsx
src/app/summary/[...path]/components/historythread.tsx
src/helpers/utils.ts

show date for posts and thread count for active discussions on homepage

---

src/app/page.tsx
src/helpers/types.ts
src/helpers/utils.ts

Removes duplicate summaries from summary list from a specific batch

fix: remove duplicate summaries

---

src/helpers/utils.ts

- This fixes the author name of the combined summaries mis-matching that of Active Discussions

fix: author name misrepresented

---

src/app/components/server/post.tsx
src/helpers/utils.ts

- Make author text display of all activity and active discussions similar

refactor: make author text display similar

---

src/app/layout.tsx
src/app/summary/[...path]/page.tsx

fixes:
- preserve new lines from source
- footer stays at bottom regardless of content

Preserve new lines

---

src/app/components/server/post.tsx

fix: Add some separator between sections

---

src/app/components/client/homepage.tsx

format header summary, size down font and recognize paragraphs

---

src/app/components/client/homepage.tsx
src/app/components/client/scroll-to-top.tsx
src/app/components/server/post.tsx
src/app/globals.css
src/app/summary/[...path]/components/historythread.tsx

closes https://github.com/bitcoinsearch/tldr/issues/55 https://github.com/bitcoinsearch/tldr/issues/52

chore: adds some discussion replies enhancement 

---

src/app/components/client/hooks/use-media-query.tsx
src/app/components/client/search-modal.tsx
src/app/components/server/navbar.tsx
src/app/globals.css

closes https://github.com/bitcoinsearch/tldr/issues/56
- search boxl remains centered on mobile for easy accessiblity
- its moved to the search input position at the top right for desktop screens

chore: switch position of search bar

---

src/app/components/client/search-modal.tsx

closes https://github.com/bitcoinsearch/tldr/issues/90

fix: author input modal width

---

src/app/layout.tsx

chore: update site metadata description

---

src/app/components/server/post.tsx
src/app/summary/[...path]/components/BreadCrumb.tsx
src/app/summary/[...path]/components/historythread.tsx
src/app/summary/[...path]/page.tsx
src/helpers/types.ts
src/helpers/utils.ts

breadcrumb functionality for user navigation

---

src/app/components/client/queuer-banner.tsx
src/app/layout.tsx
src/app/summary/[...path]/components/BreadCrumb.tsx

WIP
- Fix styling for queuer banner with navbar

fix styling for queuer banner

---

src/app/components/client/homepage.tsx
src/app/components/client/subscribe-to-newsletter.tsx
src/app/components/server/newsletter.tsx
src/app/mailchimp.css

- Change the title text
- Change position of subscription form in homepage and newsletter page

Fixes for newsletter form

---

src/app/components/client/search-result-ui.tsx
src/app/components/server/newsletter.tsx

- fix for newsletter reply to navigate to discussion history

Newsletter fix

---

.github/workflows/send-newsletter.yml
package-lock.json
package.json
src/helpers/send-newsletter.ts

In this PR, 
- I set up sending the weekly  newsletter using the [generated JSON file ](https://github.com/bitcoinsearch/mailing-list-summaries/blob/bfa0c912ab926a7e0323d755389cb46a684f48a1/static/newsletters/newsletter.json) 
- Using GitHub action to trigger the newsletter.ts module(independent of the Nextjs module) every 12 pm( can be updated/changed) on Monday after the newsletter.json file has been updated. 
- To set up prod, I have a check for where the action is triggered from production or development. 
- update GitHub secrets for the following cred @Extheoisah. 
- Mail authentication needs to be set up on Mailchimp to avoid newsletters dropping into spam.

Send newsletter

---

src/app/components/server/MarkdownWrapper.tsx
src/app/summary/[...path]/page.tsx

- fix headerline text to render markdown
- make all links open on another page

fix headline text not wrapped in markdown wrapper

---

src/helpers/send-newsletter.ts

This PR fixes issue #210 to update the fields and take care of empty values for summary details(keys)

fix: issue #210

---

src/app/summary/[...path]/page.tsx

add published date

---

src/app/components/server/post.tsx
src/helpers/utils.ts

- Remove thread replies checker

fix thread replies

---

src/app/components/client/homepage.tsx

- Add conditional to render fallback text when homepage data summaries are null

Add fallback for null/empty results

---

src/app/newsletter/page.tsx
src/app/summary/[...path]/components/historythread.tsx
src/app/summary/[...path]/page.tsx
src/config/config.ts
src/helpers/types.ts
src/helpers/utils.ts

Get post replies from combined summary

fix(newsletter): Reply count

---

src/app/components/server/post.tsx

Fix grammatical error when displaying contributors under involving section when remaining contributor count is equal to one

Fix: Authors display in post component

---

.gitignore
src/helpers/send-newsletter.ts

A new email template for TLDR weekly newsletter

New email template

---

src/app/not-found.tsx

This pr adds a custom error page to be displayed when the user navigates to a non-existent page

feat: add custom error page

---

src/app/summary/[...path]/components/thread-summary.tsx

This PR Makes BreadCrumb Post Link work as expected when click. Previously  when clicked it does nothing.
Below is an Example of Before and After
Before:
https://github.com/user-attachments/assets/56609971-8118-444f-aaa5-e62aac3ee06b
After:
https://github.com/user-attachments/assets/4de8b563-48ad-44eb-b84a-58fe4b812fec
[Preview Link](https://tldr-86f0d8rye-btc-knowledge-base.vercel.app/summary/bitcoin-dev/Feb_2025/combined_P2QRH-BIP-360-Update?replies=17)

Breadcrumb Post Link not working

---

src/app/components/client/footer.tsx

This PR changes our feedback link to google

Changed feedback link to google

---

package-lock.json
package.json
src/app/components/client/footer.tsx

This PR adds our linkedin link with the Icon to the footer section

Add linkedin icon

---

src/helpers/send-newsletter.ts

This fixes the issue of text being cut of in few of the newsletter, it limits it to at most 4 paragraphs

Newsletter Summary Cut

---

src/app/layout.tsx

This PR changes the metadata description also increases the image shown on preview

Preview metadata
